<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            // ... keep your existing 20 records here ...

            // New Khmer name entries starting from UID00021
            [
                'user_id' => 'UID'.str_pad(21, 5, '0', STR_PAD_LEFT),
                'name' => 'Sok Chanboramey',
                'email' => 'chanboramey.sok@example.com',
                'date_of_birth' => '1990-08-15',
                'join_date' => '2022-01-10',
                'phone_number' => '012345678',
                'status' => 'Active',
                'role_name' => 'Admin',
                'avatar' => 'default.png',
                'position' => 'IT Manager',
                'department' => 'Technology',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(22, 5, '0', STR_PAD_LEFT),
                'name' => 'Lim Sopheak',
                'email' => 'sopheak.lim@example.com',
                'date_of_birth' => '1992-05-22',
                'join_date' => '2021-11-15',
                'phone_number' => '023456789',
                'status' => 'Active',
                'role_name' => 'Manager',
                'avatar' => 'default.png',
                'position' => 'Operations Manager',
                'department' => 'Operations',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(23, 5, '0', STR_PAD_LEFT),
                'name' => 'Kong Vichheka',
                'email' => 'vichheka.kong@example.com',
                'date_of_birth' => '1988-11-05',
                'join_date' => '2020-09-20',
                'phone_number' => '034567890',
                'status' => 'Active',
                'role_name' => 'Developer',
                'avatar' => 'default.png',
                'position' => 'Senior Developer',
                'department' => 'IT',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(24, 5, '0', STR_PAD_LEFT),
                'name' => 'Heng Samnang',
                'email' => 'samnang.heng@example.com',
                'date_of_birth' => '1993-07-30',
                'join_date' => '2021-04-05',
                'phone_number' => '045678901',
                'status' => 'Active',
                'role_name' => 'Designer',
                'avatar' => 'default.png',
                'position' => 'UI/UX Designer',
                'department' => 'Design',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(25, 5, '0', STR_PAD_LEFT),
                'name' => 'Chhay Raksmey',
                'email' => 'raksmey.chhay@example.com',
                'date_of_birth' => '1989-09-12',
                'join_date' => '2020-08-18',
                'phone_number' => '056789012',
                'status' => 'Active',
                'role_name' => 'HR',
                'avatar' => 'default.png',
                'position' => 'HR Specialist',
                'department' => 'Human Resources',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(26, 5, '0', STR_PAD_LEFT),
                'name' => 'Yim Sotheary',
                'email' => 'sotheary.yim@example.com',
                'date_of_birth' => '1994-04-25',
                'join_date' => '2021-06-22',
                'phone_number' => '067890123',
                'status' => 'Active',
                'role_name' => 'Accountant',
                'avatar' => 'default.png',
                'position' => 'Senior Accountant',
                'department' => 'Finance',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(27, 5, '0', STR_PAD_LEFT),
                'name' => 'Nhem Kosal',
                'email' => 'kosal.nhem@example.com',
                'date_of_birth' => '1991-12-08',
                'join_date' => '2020-12-30',
                'phone_number' => '078901234',
                'status' => 'Active',
                'role_name' => 'Developer',
                'avatar' => 'default.png',
                'position' => 'Backend Developer',
                'department' => 'IT',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(28, 5, '0', STR_PAD_LEFT),
                'name' => 'Ouk Malis',
                'email' => 'malis.ouk@example.com',
                'date_of_birth' => '1995-02-14',
                'join_date' => '2022-02-12',
                'phone_number' => '089012345',
                'status' => 'Active',
                'role_name' => 'Marketing',
                'avatar' => 'default.png',
                'position' => 'Digital Marketer',
                'department' => 'Marketing',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(29, 5, '0', STR_PAD_LEFT),
                'name' => 'Chea Sovannary',
                'email' => 'sovannary.chea@example.com',
                'date_of_birth' => '1987-10-19',
                'join_date' => '2021-09-05',
                'phone_number' => '090123456',
                'status' => 'Active',
                'role_name' => 'Sales',
                'avatar' => 'default.png',
                'position' => 'Sales Executive',
                'department' => 'Sales',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 'UID'.str_pad(30, 5, '0', STR_PAD_LEFT),
                'name' => 'Prak Monyroth',
                'email' => 'monyroth.prak@example.com',
                'date_of_birth' => '1996-05-03',
                'join_date' => '2022-03-17',
                'phone_number' => '001234567',
                'status' => 'Active',
                'role_name' => 'Support',
                'avatar' => 'default.png',
                'position' => 'Customer Support',
                'department' => 'Support',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('users')->insert($users);
    }
}
